name: Docker Image CI

on:
 workflow_dispatch:
    inputs:
      repo:
        description: Name of the repo
        required: true
        default: 'zharec'
        type: string
      image:
        description: Name of the image
        required: true
        default: 'week-2-prefect-agent'
        type: string
      tag:
        description: Tag of the image
        required: true
        default: 'latest'
        type: string
        
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.event.inputs.image }}

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Week_2/solution


    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
       touch login.sh
       echo "prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace ${{ secrets.PREFECT_WORKSPACE_NAME }}" >> login.sh
       docker build -t ${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} .
       docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }} 
       docker tag ${{ github.event.inputs.image }}:${{ github.event.inputs.tag }} ${{ github.event.inputs.repo }}/${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
       
