name: Docker Image CI

on:
 workflow_dispatch:
    inputs:
      image:
        description: Name of the image
        required: true
        default: 'zharec-week-2-prefect-agent'
        type: string

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Week_2/solution


    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       touch login.sh
       echo "prefect cloud login --key ${{ secrets.PREFECT_API_KEY }} --workspace ${{ secrets.PREFECT_WORKSPACE_NAME }}" >> login.sh
       docker build -t ${{ github.event.inputs.image }}:$(date +%s) .
